[package]
name = "learning"
version = "0.1.0"
authors = ["“Joel <jdesa002@odu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rand = "0.8.4"
clearscreen = "1.0.9"